// Dao Constants
export const FETCH_DAOS_BEGIN = 'FETCH_DAOS_BEGIN'
export const FETCH_DAOS_ERROR = 'FETCH_DAOS_ERROR'
export const FETCH_DAOS_SUCCESS = 'FETCH_DAOS_SUCCESS'

export const FETCH_DAO_BEGIN = 'FETCH_DAO_BEGIN'
export const FETCH_DAO_ERROR = 'FETCH_DAO_ERROR'
export const FETCH_DAO_SUCCESS = 'FETCH_DAO_SUCCESS'

export const CREATE_DAO_BEGIN = 'CREATE_DAO_BEGIN'
export const CREATE_DAO_ERROR = 'CREATE_DAO_ERROR'
export const CREATE_DAO_SUCCESS = 'CREATE_DAO_SUCCESS'

export const DELETE_DAO_BEGIN = 'DELETE_DAO_BEGIN'
export const DELETE_DAO_ERROR = 'DELETE_DAO_ERROR'
export const DELETE_DAO_SUCCESS = 'DELETE_DAO_SUCCESS'

// Status Constants
export const FETCH_STATUSES_BEGIN = 'FETCH_STATUSES_BEGIN'
export const FETCH_STATUSES_ERROR = 'FETCH_STATUSES_ERROR'
export const FETCH_STATUSES_SUCCESS = 'FETCH_STATUSES_SUCCESS'

export const CREATE_STATUS_BEGIN = 'CREATE_STATUS_BEGIN'
export const CREATE_STATUS_ERROR = 'CREATE_STATUS_ERROR'
export const CREATE_STATUS_SUCCESS = 'CREATE_STATUS_SUCCESS'

export const DELETE_STATUS_BEGIN = 'DELETE_STATUS_BEGIN'
export const DELETE_STATUS_ERROR = 'DELETE_STATUS_ERROR'
export const DELETE_STATUS_SUCCESS = 'DELETE_STATUS_SUCCESS'

export const EDIT_STATUS_BEGIN = 'EDIT_STATUS_BEGIN'
export const EDIT_STATUS_ERROR = 'EDIT_STATUS_ERROR'
export const EDIT_STATUS_SUCCESS = 'EDIT_STATUS_SUCCESS'

// Blockchain Constants
export const FETCH_BLOCKCHAINS_BEGIN = 'FETCH_BLOCKCHAINS_BEGIN'
export const FETCH_BLOCKCHAINS_ERROR = 'FETCH_BLOCKCHAINS_ERROR'
export const FETCH_BLOCKCHAINS_SUCCESS = 'FETCH_BLOCKCHAINS_SUCCESS'

export const CREATE_BLOCKCHAIN_BEGIN = 'CREATE_BLOCKCHAIN_BEGIN'
export const CREATE_BLOCKCHAIN_ERROR = 'CREATE_BLOCKCHAIN_ERROR'
export const CREATE_BLOCKCHAIN_SUCCESS = 'CREATE_BLOCKCHAIN_SUCCESS'

export const DELETE_BLOCKCHAIN_BEGIN = 'DELETE_BLOCKCHAIN_BEGIN'
export const DELETE_BLOCKCHAIN_ERROR = 'DELETE_BLOCKCHAIN_ERROR'
export const DELETE_BLOCKCHAIN_SUCCESS = 'DELETE_BLOCKCHAIN_SUCCESS'

export const EDIT_BLOCKCHAIN_BEGIN = 'EDIT_BLOCKCHAIN_BEGIN'
export const EDIT_BLOCKCHAIN_ERROR = 'EDIT_BLOCKCHAIN_ERROR'
export const EDIT_BLOCKCHAIN_SUCCESS = 'EDIT_BLOCKCHAIN_SUCCESS'

// Framework Constants
export const FETCH_FRAMEWORKS_BEGIN = 'FETCH_FRAMEWORKS_BEGIN'
export const FETCH_FRAMEWORKS_ERROR = 'FETCH_FRAMEWORKS_ERROR'
export const FETCH_FRAMEWORKS_SUCCESS = 'FETCH_FRAMEWORKS_SUCCESS'

export const CREATE_FRAMEWORK_BEGIN = 'CREATE_FRAMEWORK_BEGIN'
export const CREATE_FRAMEWORK_ERROR = 'CREATE_FRAMEWORK_ERROR'
export const CREATE_FRAMEWORK_SUCCESS = 'CREATE_FRAMEWORK_SUCCESS'

export const DELETE_FRAMEWORK_BEGIN = 'DELETE_FRAMEWORK_BEGIN'
export const DELETE_FRAMEWORK_ERROR = 'DELETE_FRAMEWORK_ERROR'
export const DELETE_FRAMEWORK_SUCCESS = 'DELETE_FRAMEWORK_SUCCESS'

export const EDIT_FRAMEWORK_BEGIN = 'EDIT_FRAMEWORK_BEGIN'
export const EDIT_FRAMEWORK_ERROR = 'EDIT_FRAMEWORK_ERROR'
export const EDIT_FRAMEWORK_SUCCESS = 'EDIT_FRAMEWORK_SUCCESS'
