export const FETCH_DAOS_BEGIN = 'FETCH_DAOS_BEGIN'
export const FETCH_DAOS_ERROR = 'FETCH_DAOS_ERROR'
export const FETCH_DAOS_SUCCESS = 'FETCH_DAOS_SUCCESS'

export const FETCH_DAO_BEGIN = 'FETCH_DAO_BEGIN'
export const FETCH_DAO_ERROR = 'FETCH_DAO_ERROR'
export const FETCH_DAO_SUCCESS = 'FETCH_DAO_SUCCESS'

export const FETCH_STATUSES_BEGIN = 'FETCH_STATUSES_BEGIN'
export const FETCH_STATUSES_ERROR = 'FETCH_STATUSES_ERROR'
export const FETCH_STATUSES_SUCCESS = 'FETCH_STATUSES_SUCCESS'

export const CREATE_STATUS_BEGIN = 'CREATE_STATUS_BEGIN'
export const CREATE_STATUS_ERROR = 'CREATE_STATUS_ERROR'
export const CREATE_STATUS_SUCCESS = 'CREATE_STATUS_SUCCESS'

export const DELETE_STATUS_BEGIN = 'DELETE_STATUS_BEGIN'
export const DELETE_STATUS_ERROR = 'DELETE_STATUS_ERROR'
export const DELETE_STATUS_SUCCESS = 'DELETE_STATUS_SUCCESS'

export const EDIT_STATUS_BEGIN = 'EDIT_STATUS_BEGIN'
export const EDIT_STATUS_ERROR = 'EDIT_STATUS_ERROR'
export const EDIT_STATUS_SUCCESS = 'EDIT_STATUS_SUCCESS'
