export const FETCH_DAOS_BEGIN = 'FETCH_DAOS_BEGIN'
export const FETCH_DAOS_ERROR = 'FETCH_DAOS_ERROR'
export const FETCH_DAOS_SUCCESS = 'FETCH_DAOS_SUCCESS'

export const FETCH_DAO_BEGIN = 'FETCH_DAO_BEGIN'
export const FETCH_DAO_ERROR = 'FETCH_DAO_ERROR'
export const FETCH_DAO_SUCCESS = 'FETCH_DAO_SUCCESS'
