import resourceReducer from './_baseResourceReducer'

import {
  FETCH_BLOCKCHAINS_SUCCESS,
  FETCH_BLOCKCHAIN_SUCCESS,
  CREATE_BLOCKCHAIN_SUCCESS,
  DELETE_BLOCKCHAIN_SUCCESS,
  EDIT_BLOCKCHAIN_SUCCESS
} from '../constants/actionTypes'

export default resourceReducer(
  FETCH_BLOCKCHAINS_SUCCESS,
  FETCH_BLOCKCHAIN_SUCCESS,
  CREATE_BLOCKCHAIN_SUCCESS,
  DELETE_BLOCKCHAIN_SUCCESS,
  EDIT_BLOCKCHAIN_SUCCESS
)
