import resourceReducer from './_baseResourceReducer'

import {
  FETCH_CONTRIBUTORS_SUCCESS,
  FETCH_CONTRIBUTOR_SUCCESS,
  CREATE_CONTRIBUTOR_SUCCESS,
  DELETE_CONTRIBUTOR_SUCCESS,
  EDIT_CONTRIBUTOR_SUCCESS
} from '../constants/actionTypes'

export default resourceReducer(
  FETCH_CONTRIBUTORS_SUCCESS,
  FETCH_CONTRIBUTOR_SUCCESS,
  CREATE_CONTRIBUTOR_SUCCESS,
  DELETE_CONTRIBUTOR_SUCCESS,
  EDIT_CONTRIBUTOR_SUCCESS
)
