import resourceReducer from './_baseResourceReducer'

import {
  FETCH_DAOS_SUCCESS,
  FETCH_DAO_SUCCESS,
  CREATE_DAO_SUCCESS,
  DELETE_DAO_SUCCESS,
  EDIT_DAO_SUCCESS,
  CREATE_DAO_CHILD_SUCCESS,
  DELETE_DAO_CHILD_SUCCESS,
  EDIT_DAO_CHILD_SUCCESS,
  LINK_DAO_RESOURCE_SUCCESS
} from '../constants/actionTypes'

export default resourceReducer(
  FETCH_DAOS_SUCCESS,
  FETCH_DAO_SUCCESS,
  CREATE_DAO_SUCCESS,
  DELETE_DAO_SUCCESS,
  EDIT_DAO_SUCCESS,
  CREATE_DAO_CHILD_SUCCESS,
  DELETE_DAO_CHILD_SUCCESS,
  EDIT_DAO_CHILD_SUCCESS,
  LINK_DAO_RESOURCE_SUCCESS
)
